/**
 * Deletes all Hindi and Marathi translations from project_translations
 * and event_translations that were auto-generated by the old MyMemory API.
 * English translations are kept intact.
 *
 * Run: npx tsx script/clear-auto-translations.ts
 */

import "dotenv/config";
import { db } from "../server/db";
import { projectTranslations, eventTranslations } from "../shared/schema";
import { inArray } from "drizzle-orm";

async function main() {
  const deletedProjects = await db
    .delete(projectTranslations)
    .where(inArray(projectTranslations.language, ["hi", "mr"]))
    .returning({ id: projectTranslations.id, language: projectTranslations.language, title: projectTranslations.title });

  const deletedEvents = await db
    .delete(eventTranslations)
    .where(inArray(eventTranslations.language, ["hi", "mr"]))
    .returning({ id: eventTranslations.id, language: eventTranslations.language, title: eventTranslations.title });

  console.log(`\nDeleted ${deletedProjects.length} project translation(s):`);
  deletedProjects.forEach((r) => console.log(`  [${r.language}] ${r.title}`));

  console.log(`\nDeleted ${deletedEvents.length} event translation(s):`);
  deletedEvents.forEach((r) => console.log(`  [${r.language}] ${r.title}`));

  console.log("\nDone. English translations are untouched.");
  process.exit(0);
}

main().catch((err) => { console.error(err); process.exit(1); });
